import { prismaClient } from "@uptimematrix/store";
import { getStreamLength, xAddBulk, xGroupCreate, STREAM_NAME } from "@uptimematrix/redisstream/client";


const GROUP_NAME = process.env.GROUP_NAME!;

async function main(){
    console.log("pusher started");
    console.log("GROUP_NAME in pusher:", GROUP_NAME);
    console.log(`Calling xGroupCreate for stream ${STREAM_NAME} and group ${GROUP_NAME}`);
    await xGroupCreate(STREAM_NAME, GROUP_NAME);
    console.log(`xGroupCreate call completed.`);
    let websites = await prismaClient.website.findMany({
        select:{//this will help to get only url and id not all fileds.
            url:true,
            id:true,
        }
    })
    await xAddBulk(websites.map(w=>({
        url:w.url,
        id:w.id //this id is generated by redis and is unique for each message.
    })))
}

setInterval(()=>{
    main()
},10000)

main();