import { prismaClient } from "store/client";
import { getStreamLength, xAddBulk } from "redisstream/client";


async function main(){
    console.log("pusher started");
    let websites = await prismaClient.website.findMany({
        select:{//this will help to get only url and id not all fileds.
            url:true,
            id:true,
        }
    })
    console.log("pusher done",await getStreamLength());
    await xAddBulk(websites.map(w=>({
        url:w.url,
        id:w.id //this id is generated by redis and is unique for each message.
    })))
}

setInterval(()=>{
    main()
},3*1000*60)

main();